---
title: "R Package Development and Validation"
subtitle: "Welcome and Orientation"
author: "Ellis Hughes & Marie Vendettuoli"
date: "2021/06/04"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r include = FALSE}

# remotes::install_github("mitchelloharawild/icons")
library(icons)
# download_fontawesome()

```

class: inverse, center, middle

# Instructors

---

# Ellis Hughes

- Statistical Programmer
  - Statistical Genetics
  - HIV Vaccine Research

- Community Involvement
  - Seattle UseR Organizer
  - TidyX Screencast
  
- <a href = 'https://twitter.com/ellis_hughes'>`r icons::fontawesome("twitter")` @ellis_hughes</a>
- <a href = 'https://github.com/thebioengineer'>`r icons::fontawesome("github")` thebioengineer</a>
        
        
---

# Marie Vendettuoli

- Statistical Programmer/Data Scientist
  - USDA-APHIS
  - HIV Vaccine Research


- <a href = 'https://github.com/mariev'>`r icons::fontawesome("github")` mariev </a>

---

class: inverse, center, middle

# Goals of the Workshop

---

## Goals

--

1. An understanding of basic package development

  - Structure
  - Function writing
  - Documentation

--

2. How to Validate an R Package

  - what is validation
  - the R Package validation Framework
  - {valtools} R package
  
---

## Workshop COC

- Please review the [Cascadia R Conference Code of Conduct](https://cascadiarconf.com/policies/). 

- Issues can be brought to our attention by
  - contact an organizer
  - email `cascadiarcon@gmail.com` 

- Please do not record this workshop to respect the privacy of others.

<br>

We do this to create an open, collaborative space where people can feel comfortable to learn and grow.

---

## Workshop Materials

[https://github.com/FredHutch/R_Package_Validation_Tutorial](https://github.com/FredHutch/R_Package_Validation_Tutorial)

- Materials are the exercises, available under `Materials`
- Slides are what we present, available under `Slides`

<br>

- Workshop materials are available online now and after the conference

<br>

- [Live chat on Slack!](https://app.slack.com/client/T5FG0LBND/C0224NFG5TR)
  - [Cascadia R Conf Slack](https://join.slack.com/t/cascadiarconf/shared_invite/zt-49gyix45-3kJ7Meg6DaVh1W6tTC6yNw)
  - `workshops-2021-r-package-validation`

---
class: inverse, center, middle

## What ifs

---

class: center, middle

What if this is too much?!

---

class: center, middle

What if this is too basic?!

---

class: center, middle

What if we are in the middle of a pandemic, there are killer bees, and ...!?

---

class: inverse, center, middle

## Ready? Lets Go!




